# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
title: 'Gustavo Costa'
email: 'gustavo@arcos.org.br'
description: >-
    Interdisciplinary researcher in data science and AI ethics, transitioning from a background in psychotherapy and philosophy of science.
baseurl: ''
url: 'https://noah-art3mis.github.io'
github_username: 'noah-art3mis'
linkedin_username: 'gustavoarcos'
bluesky_username: '@simulacro.bsky.social'
mastodon_username: '@noah_artemis@gamedev.place'
instagram_username: '@simulacro.psi'

# Author information
author:
    name: 'Gustavo Costa'
    bio: 'Interdisciplinary researcher in data science and AI ethics'
    location: 'London, UK'
    phone: '+44 7502 445416'
    website: 'noah-art3mis.github.io'

# Theme configuration - using remote_theme for latest version
remote_theme: jekyll/minima
minima:
    # skin: dark
    skin: classic
    date_format: '%b %-d, %Y'

# Build settings
markdown: kramdown
plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-remote-theme

# Collections
collections:
    projects:
        output: true
        permalink: /projects/:title/

# Defaults
defaults:
    - scope:
          path: ''
          type: 'posts'
      values:
          layout: 'post'
          author: 'Gustavo Costa'
    - scope:
          path: ''
          type: 'projects'
      values:
          layout: 'project'
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
