# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
title: 'Gustavo Costa'
email: 'gustavo.costa@lis.ac.uk'
baseurl: ''
url: 'https://noah-art3mis.github.io'

# Social media links (these appear in the footer)
github_username: 'noah-art3mis'
linkedin_username: 'gustavoarcos'
instagram_username: 'simulacro.psi'
bluesky_username: 'simulacro.bsky.social'
mastodon_username: 'noah_artemis@gamedev.place'

# Author information
# author:
#     name: 'Gustavo Costa'
#     bio: 'Interdisciplinary researcher in data science and AI ethics'
#     location: 'London, UK'
#     phone: '+44 7502 445416'
#    website: 'noah-art3mis.github.io'

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag

# Collections
collections:
    projects:
        output: true
        permalink: /projects/:title/

# Defaults
defaults:
    - scope:
          path: ''
          type: 'posts'
      values:
          layout: 'post'
          author: 'Gustavo Costa'
    - scope:
          path: ''
          type: 'projects'
      values:
          layout: 'project'
